/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "jni_MainActivity.h"
#include <android/log.h>
/* Header for class com_example_testjni_MainActivity */

/*
 * Class:     com_example_testjni_MainActivity
 * Method:    sendObject
 * Signature: (I)V
 * jclass gJniCdeApiCls;
 */
const char* kJavActivityClassPath = "com/example/testjni/MainActivity";
const char *memberIdentityPath = "com/example/testjni/Employee";
static JNINativeMethod sMethods[] = { { "sendObject",
		"(Lcom/example/testjni/Employee;)V", (void *) sendObject } };

JNIEXPORT jint JNI_OnLoad(JavaVM *jvm, void *reserved) {
	JNIEnv *env;
	int status;
	if ((*jvm)->GetEnv(jvm, (void**) &env, JNI_VERSION_1_6) != JNI_OK) {
		return JNI_ERR;
	}

	jclass cls = (*env)->FindClass(env, kJavActivityClassPath);
	gJniCdeApiCls = (jclass) (*env)->NewGlobalRef(env, cls);
	(*env)->DeleteLocalRef(env, cls);
	if ((*env)->RegisterNatives(env, gJniCdeApiCls, sMethods,
			sizeof(sMethods) / sizeof(sMethods[0])) != JNI_OK) {
		return -1;
	}
	return JNI_VERSION_1_6;
}
void sendObject(JNIEnv *env, jobject jobj, jobject jemp) {
	char *name;
	jclass memberInfoClass = (*env)->GetObjectClass(env, jemp);
	jmethodID getMember = (*env)->GetMethodID(env, memberInfoClass, "getString",
			"()Ljava/lang/String;");
	jstring str = (jstring) (*env)->CallObjectMethod(env, jemp, getMember);

	name = (*env)->GetStringUTFChars(env, str, 0);
	__android_log_print(ANDROID_LOG_DEBUG, "AJAY JNI", "sendObject : %s", name);
}
