/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testjni_MainActivity */

#ifndef _Included_jni_MainActivity
#define _Included_jni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testjni_MainActivity
 * Method:    sendObject
 * Signature: (I)V
 */
 void  sendObject(JNIEnv* env, jobject obj,jobject memberInfo);
jclass gJniCdeApiCls;
jclass gJniMemberIdentityCls;

#ifdef __cplusplus
}
#endif
#endif
